language: cpp

compiler:
  - g++
dist: xenial

git:
  depth: 1

before_install:
  - sudo apt-get install graphviz
  - sudo apt-get install cmake

install:
  - sudo apt-get install flex=2.6.4
  - sudo apt-get install bison=3.4

script:
  - sh ./make_all.sh
