language: cpp

compiler:
  - g++
dist: xenial

git:
  depth: 1

before_install:
  - sudo apt-get install graphviz
  - sudo apt-get install cmake

install:
  - sudo apt-get install flex
  - sudo apt-get install bison

script:
  - sh ./make_all.sh
